name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: vggallery
          path: dist/vggallery.user.js

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/vggallery.user.js
